<?php
return [
    'USD' => 'USD - United States Dollar',
    'EUR' => 'EUR - Euro',
    'XAF' => 'XAF - Central African CFA Franc',
    'GBP' => 'GBP - British Pound',
    'JPY' => 'JPY - Japanese Yen',
    'CAD' => 'CAD - Canadian Dollar',
    'AUD' => 'AUD - Australian Dollar',
    'CHF' => 'CHF - Swiss Franc',
    'CNY' => 'CNY - Chinese Yuan',
    'INR' => 'INR - Indian Rupee',
    'BRL' => 'BRL - Brazilian Real',
    'ZAR' => 'ZAR - South African Rand',
    'MXN' => 'MXN - Mexican Peso',
    'SGD' => 'SGD - Singapore Dollar',
    'HKD' => 'HKD - Hong Kong Dollar',
    'NZD' => 'NZD - New Zealand Dollar',
    'SEK' => 'SEK - Swedish Krona',
    'NOK' => 'NOK - Norwegian Krone',
    'DKK' => 'DKK - Danish Krone',
    'RUB' => 'RUB - Russian Ruble',
    'KRW' => 'KRW - South Korean Won',
    'TRY' => 'TRY - Turkish Lira',
    'AED' => 'AED - United Arab Emirates Dirham',
    'SAR' => 'SAR - Saudi Riyal',
    'THB' => 'THB - Thai Baht',
    'MYR' => 'MYR - Malaysian Ringgit',
];